services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    container_name: nemestrix_db
  prod:
    image: pixlmint/nemestrix
    container_name: nemestrix_prod
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - 8082:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DbConnection=Host=db;Database=db;Username=db;Password=db
      - ASPNETCORE_ApiKey__Hash=8OTC92xYkW7CWPJGhRvqCR0U1CR6L8PhhpRGGxgW4Ts=

volumes:
  db:
