@HOST = https://nemestrix.pixlmint.ch
@APIKEY = o5hJKzQuiRDxVrfGuOen5pJ8ICPUKojuwsQCmNBmAUw

###

GET {{HOST}}
X-Api-Key: {{APIKEY}}

###

GET {{HOST}}/trees

###

GET {{HOST}}/trees/3

###

GET {{HOST}}/tree?node=Home

###

POST {{HOST}}/trees
Content-Type: application/json

{
    "label": "Home.World"
}

###

POST {{HOST}}/t
Content-Type: application/json

{
    "Test": {
        "Node2": {
            "NestedChild2": "hello2"
        }
    }
}

###

GET {{HOST}}/t?node=Test.*

###

GET {{HOST}}/t/Test.Node2.NestedChild2
X-Api-Key: {{APIKEY}}

###

DELETE {{HOST}}/t/Test.Another
X-Api-Key: {{APIKEY}}
