###

GET {{HOST}}
X-Api-Key: {{APIKEY}}

###

POST {{HOST}}/t
Content-Type: application/json
X-Api-Key: {{APIKEY}}

{
    "Test": {
        "Node2": {
            "NestedChild2": "hello2"
        }
    }
}

###

GET {{HOST}}/t?node=Test.*
X-Api-Key: {{APIKEY}}

###

GET {{HOST}}/t/Test.Node2.NestedChild2
X-Api-Key: {{APIKEY}}

###

DELETE {{HOST}}/t/Test.Another
X-Api-Key: {{APIKEY}}
